name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Checkout code
        working-directory: ./UnixScripts
        # run: echo "found folder"
        run: pwd
      - name: Check file existence
        id: check_files
        working-directory: ./UnixScripts
        run: (test -f hello.ksh && true ) || false, skipping step

      # - name: File exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   # Only runs if all of the files exists
      #   run: echo All files exists!

      - name: Directory empty
        run: ( ls ) && echo "Not Empty" || echo "Empty"
        working-directory: /home/runner/work/Batch-UNIX-scripts-gha/Batch-UNIX-scripts-gha/UnixScripts 
        # run: ( ls -A ./UnixScripts ) && echo "Not Empty" || echo "Empty"