name: Test
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: npm install
        
    - name: Overwrite Files & Directories
      run: |
        mkdir -p ./BackupUnixScripts
        gitkeep ./BackupUnixScripts
        cd ./artifacts2.0 
        git mv *.txt /home/runner/work/Test-Batch-CI-CD/Test-Batch-CI-CD/BackupUnixScripts

    - name: Overwrite Files & Directories 2
      run: |
        cd ./BackupUnixScripts
        ls -R