name: Test
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: npm install
        
    - name: Overwrite Files & Directories
      run: |
        ls 
      

    # - name: Overwrite Files & Directories 2
    #   run: |
    #     cd ./BackupUnixScripts
    #     ls -R