name: Test
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: npm install
        
    - name: Overwrite Files & Directories
      run: |
        mkdir -p .gitkeep
        cd ./.gitkeep
        mkdir -p ./BackupUnixScripts
        cd ..
        cd ./artifacts2.0 
        git mv *.ksh /home/runner/work/Test-Batch-CI-CD/Test-Batch-CI-CD/.gitkeep/BackupUnixScripts

    - name: Overwrite Files & Directories 2
      run: |
        cd ./artifacts2.0/Backup
        ls -R