name: Test
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: test
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
      
        
    - name: Overwrite Files & Directories
      run: /home/runner/work/Batch-UNIX-scripts-gha/Batch-UNIX-scripts-gha/.github/test.sh
      shell: bash

    - name: Overwrite Files & Directories 2
      run: |
        cd ./artifacts2.0/Backup
        ls -R