name: Test
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm install
      run: npm install
        
    - name: Overwrite Files & Directories
      run: |
        cd OldScripts
        echo "test" > help.txt
        git config --global user.email "yasmine.hines@aa.com"
        git config --global user.name "yasminehines"

        git add help.txt
        git commit -m "Test"
        git push
  


    # - name: Overwrite Files & Directories 2
    #   run: |
    #     cd ./BackupUnixScripts
    #     ls -R