name: Master
on:
  push:
    branches:
      - Dev
  schedule:
    - cron: '1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"