name: Test Unix Scripts Workflow


on: 
  # schedule:
  #  - cron: "0/5 * * * *" # * means any value
  #  - cron: "0/6 * * * *" #  (minute hour day(month) month day(week))
  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main repository
        uses: actions/checkout@v1
      
      - name: Check Unix Scripts Directory
        id: UnixScripts
        working-directory: ./UnixScripts
        run: |
          if [ -z "$(ls)" ]; then
              echo "Empty"
              echo '::set-output name=num::0'
          else
              echo "Not Empty"
              echo '::set-output name=num::1'
          fi

      - name: Delete Files & Directories
        if: steps.UnixScripts.outputs.num == 1
        working-directory: ./UnixScripts
        run: |
          ls

      - name: Extracts Artifacts
        if: steps.UnixScripts.outputs.num == 0
        run: |
          echo "Extract Artifacts"

      # - name: Deploy Unix Scripts
      #   run:  |
      #     echo "Deploying the new Unix Scripts."
      #   deploy the new Unix scripts   
      #     echo "New Unix Scripts have been deployed."